/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    MainContents: typeof import('./src/components/MainContents.vue')['default']
    Memo: typeof import('./src/components/Memo.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    TabButton: typeof import('./src/components/TabButton.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
  }
}
