name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install Dependencies
        run: yarn install
      - name: Build Electron App
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            yarn run app:build:mac
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            yarn run app:build:win
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            yarn run app:build:linux
          fi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: |
            release/**/*.dmg
            release/**/*.exe
            release/**/*.AppImage
            release/**/*.snap

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v2
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/**/*.dmg
            release/**/*.exe
            release/**/*.AppImage
            release/**/*.snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
